name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t static-site-generator .

      - name: Run the static site generator
        run: docker run -v ${{ github.workspace }}/static_site:/app/static_site static-site-generator
      
      - name: List files before uploading artifact
        run: ls -la ./static_site

      - name: Upload static site files
        uses: actions/upload-artifact@v3
        with:
          name: static-site
          path: ./static_site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download static site files
        uses: actions/download-artifact@v3
        with:
          name: static-site
          path: ./static_site
      
      - name: List files before uploading artifact
        run: ls -la ./static_site

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync ./static_site s3://${{ secrets.AWS_S3_BUCKET }} --delete --acl public-read
